### ISSUE TITLE
Maximum number of attempts to check the test status

### ISSUE THREAD

**Issue by s-mohanasundaram** [RomanAbashin/rgtmx#3]
It would be good if we have a defined number of maximum retries. I would suggest to have an argument for the same in the `start_test()` function, say `max.retry`. If the test is not successful after `max.retry`, it should return error.

**Comment by rrmn** [comment]
@s-mohanasundaram Thanks for the suggestion.

I'm asking myself what's the better approach here: 

* `max_retries` (e.g. stop pinging for the report after 10 tries)
* a flexible `ping-interval` (e.g. ping every ~5 seconds instead of ~3)
* a `max_runtime` (e.g. stop pinging after 15 seconds, no matter how many retries)
*  a combination of the above?

What's more usable from your perspective?

**Comment by s-mohanasundaram** [comment]
These suggestions are based on my experience when I ran the tests in a loop:

- `max_retries`: Depending on the duration of ping interval. I could see on an average, each test takes 20-30 seconds. 
- `ping_interval`: The first attempt can be of 15 seconds. The subsequent attempts can be of 5 seconds.
- `max_runtime`: I would suggest to have the default value as 120 seconds

I also found that if an url is not supported for test (e.g.: certificate error), gtmetrix is not giving any error alert. I thing setting the `max_runtime` would help in such case,

Further, I also tried building a similar package with your suggestions. I tried to include a named vector of urls as argument, and used `sapply `to get the results in a matrix. Since, you have completed building the package i dropped that idea.

**Comment by rrmn** [comment]
@s-mohanasundaram Thanks. I took some time to think about this. 

Wouldn’t in that case it make sense to shoot out, let’s say, 10 tests without waiting for the results, and then pull the reports via ID later?

**Comment by s-mohanasundaram** [comment]
That would be more efficient I think. It would reduce the wait time for individual reports.

**Comment by rrmn** [comment]
What about something like

```r
# define urls to test
sites <- data.frame(
    # max. 2 pending tests in free account
    url = c("google.com", "amazon.com"),
    id = NA
)

# start tests, get test ID's
for (i in 1:nrow(sites)) {
    res <- start_test(sites$url[i], "[API_KEY]", wait_for_completion = FALSE)
    sites$id[i] <- res$id
}
```
Which leads to:
```r
# urls with test ID's
> sites
         url       id
1 google.com 6aRW0Wqu
2 amazon.com HBe07Lnz
```

Then you can, after some time:
```r
# get tests/reports of test ID's
result <- NULL

for (i in 1:nrow(sites)) {
    result <- rbind(result, get_test(sites$id[i], "[API_KEY]"))
}
```
Which results in
```r
# data.frame of tests (prettified with `tibble`)
> dplyr::tibble(result)
# A tibble: 2 × 35
  id       type   attributes.struct… attributes.sour… attributes.speed…
  <chr>    <chr>               <int> <chr>                        <int>
1 4oDptTf2 report                 99 api                            314
2 xYbHS5F1 report                 76 api                           4576
# … with 30 more variables: attributes.onload_time <int>,
#   attributes.browser <chr>, attributes.redirect_duration <int>,
#   attributes.first_paint_time <int>,
#   attributes.dom_content_loaded_duration <int>,
#   attributes.dom_content_loaded_time <int>,
#   attributes.dom_interactive_time <int>,
#   attributes.page_requests <int>, attributes.page_bytes <int>, …
```

**Comment by s-mohanasundaram** [comment]
This looks good. I would suggest one more enhancement in terms of names. It would be better, if the result has names and/or urls in the first column (Either by taking input from named vector or from an argument identifying the names of the urls supplied).

**Comment by rrmn** [comment]
@s-mohanasundaram 
That could be pretty easy to achieve if you just attach the `sites` to the `result` table.
E.g., you could modify the last code chunk to

```
result <- NULL

for (i in 1:nrow(sites)) {
    result <- rbind(result, get_test(sites$id[i], "[API_KEY]"))
}

# Add first column of `sites` to result
result <- cbind(
    sites[, 1],
    result
)
```
