### ISSUE TITLE
Error in get_test - test ID as a character string

### ISSUE THREAD

**Issue by s-mohanasundaram** [RomanAbashin/rgtmx#4]
The function is working fine in Windows. 
When I tried this on Linux, I'm getting this error
```
Error in get_test(data$id, api_key, wait_for_completion = TRUE) : 
  Please enter the test ID as a character string
```

**Comment by rrmn** [comment]
@s-mohanasundaram Could you share the exact code (minus the API key)?

**Comment by s-mohanasundaram** [comment]
This is the code I used:

```
ur <- c("Chicago State University" = "https://www.csu.edu/", 
        "University of California, Irvine" = "https://uci.edu/", 
        "University of Iowa " = "https://uiowa.edu/")

loc <- 1

Rep <- list()
for (i in 1:length(ur)) {
  Rep[[names(ur[i])]] <- unlist(start_test(url = ur[i], api_key = api_key, location = loc))
  
}
```
The error:
```
Error in get_test(data$id, api_key, wait_for_completion = TRUE) : 
  Please enter the test ID as a character string

```

**I am running this code in a cloud environment which is Linux based.**

**Comment by rrmn** [comment]
@s-mohanasundaram Are you 100% sure about the code and could you double check? In the above snippet you used both `ur` and `urls`.

If it still doesn't run, can you run `sessionInfo()` and drop the output here?

**Comment by s-mohanasundaram** [comment]
I'm sorry. I've edited the code. The problem still persists.

**Comment by s-mohanasundaram** [comment]
Session Info:
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS:   /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readxl_1.3.1 rgtmx_0.1.0  cli_3.1.0   

loaded via a namespace (and not attached):
 [1] httr_1.4.2        compiler_3.6.3    R6_2.5.1          assertthat_0.2.1  tools_3.6.3       withr_2.4.2      
 [7] rstudioapi_0.10   curl_4.3.2        Rcpp_1.0.1        crayon_1.3.4      cellranger_1.1.0  jsonlite_1.7.2   
[13] rlang_0.4.12      sessioninfo_1.1.1
```

**Comment by rrmn** [comment]
@s-mohanasundaram Thank you. It seems to me that the culprit could be the old R version (`v3.6.3`) running on your Linux machine. The default value of `as.data.frame()`'s `stringsAsFactors` argument changed from `TRUE` to `FALSE` around `R v4.0.0`. Therefore the test ID, which is a string, was returned as a factor variable instead of character (as expected by the code). 

Bug fix incoming.

**Comment by rrmn** [comment]
@s-mohanasundaram   Please reinstall the package on your Linux machine and check if the issue could be fixed.

**Comment by s-mohanasundaram** [comment]
Thank you! It is working now.

**Comment by rrmn** [comment]
Fixed by https://github.com/RomanAbashin/rgtmx/commit/49a59fd5d6727af86c29e9ef1e4d2ed0bf8a4bbee
